# Generated by Django 3.2.11 on 2022-03-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_question_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
