# Generated by Django 3.2.11 on 2022-03-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
